from django.urls import path

from .django_views import (
    CaptureStatusView,
    CaptureUploadView,
    CancelView,
    ConsultView,
    ConfirmView,
    ClientCheckView,
    FormerRecommendationView,
    LoginView,
    RecommendationView,
    RegisterView,
    SurveyView,
    TrendView,
)
from .admin_views import (
    ActiveClientSessionsView,
    AdminLoginView,
    AdminProfileView,
    AdminRegisterView,
    AdminClientDetailView,
    AdminClientRecommendationView,
    AdminDashboardView,
    AdminTrendReportView,
    AllClientsView,
    ConsultationCloseView,
    ConsultationNoteView,
    StyleReportView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/check/', ClientCheckView.as_view(), name='check'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('survey/', SurveyView.as_view(), name='survey'),
    path('capture/upload/', CaptureUploadView.as_view(), name='upload'),
    path('capture/status/', CaptureStatusView.as_view(), name='capture-status'),
    path('analysis/former-recommendations/', FormerRecommendationView.as_view(), name='former-recommendations'),
    path('analysis/recommendations/', RecommendationView.as_view(), name='recommendations'),
    path('analysis/trend/', TrendView.as_view(), name='trend'),
    path('analysis/confirm/', ConfirmView.as_view(), name='confirm'),
    path('analysis/cancel/', CancelView.as_view(), name='cancel'),
    path('analysis/consult/', ConsultView.as_view(), name='consult'),
    path('admin/auth/register/', AdminRegisterView.as_view(), name='admin-register'),
    path('admin/auth/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/auth/me/', AdminProfileView.as_view(), name='admin-profile'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/clients/active/', ActiveClientSessionsView.as_view(), name='admin-active-clients'),
    path('admin/clients/', AllClientsView.as_view(), name='admin-clients'),
    path('admin/clients/detail/', AdminClientDetailView.as_view(), name='admin-client-detail'),
    path('admin/clients/recommendations/', AdminClientRecommendationView.as_view(), name='admin-client-recommendations'),
    path('admin/consultations/note/', ConsultationNoteView.as_view(), name='admin-consultation-note'),
    path('admin/consultations/close/', ConsultationCloseView.as_view(), name='admin-consultation-close'),
    path('admin/trend-report/', AdminTrendReportView.as_view(), name='admin-trend-report'),
    path('admin/style-report/', StyleReportView.as_view(), name='admin-style-report'),
]

