# Generated by Django 5.0.14 on 2026-04-10 23:45

from django.db import migrations, models


def _ensure_client_session_notes_bridge_columns(apps, schema_editor):
    connection = schema_editor.connection
    table_names = set(connection.introspection.table_names())
    if "client_session_notes" not in table_names:
        return

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                ALTER TABLE client_session_notes
                ADD COLUMN IF NOT EXISTS legacy_client_ref_id VARCHAR(255)
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS client_session_notes_legacy_client_ref_id_idx
                ON client_session_notes (legacy_client_ref_id)
                """
            )
            return

        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "client_session_notes")
        }
        if "legacy_client_ref_id" not in columns:
            cursor.execute(
                """
                ALTER TABLE client_session_notes
                ADD COLUMN legacy_client_ref_id VARCHAR(255)
                """
            )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS client_session_notes_legacy_client_ref_id_idx
            ON client_session_notes (legacy_client_ref_id)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0015_clientprofilenote"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _ensure_client_session_notes_bridge_columns,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="clientsessionnote",
                    name="consultation",
                ),
                migrations.RemoveField(
                    model_name="clientsessionnote",
                    name="client",
                ),
                migrations.RemoveField(
                    model_name="clientsessionnote",
                    name="admin",
                ),
                migrations.RemoveField(
                    model_name="clientsessionnote",
                    name="designer",
                ),
                migrations.AddField(
                    model_name="clientsessionnote",
                    name="consultation_ref_id",
                    field=models.BigIntegerField(db_column="consultation_id", db_index=True),
                ),
                migrations.AddField(
                    model_name="clientsessionnote",
                    name="client_ref_id",
                    field=models.BigIntegerField(db_column="client_id", db_index=True),
                ),
                migrations.AddField(
                    model_name="clientsessionnote",
                    name="legacy_client_ref_id",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="clientsessionnote",
                    name="admin_ref_id",
                    field=models.BigIntegerField(
                        blank=True,
                        db_column="admin_id",
                        db_index=True,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="clientsessionnote",
                    name="designer_ref_id",
                    field=models.BigIntegerField(
                        blank=True,
                        db_column="designer_id",
                        db_index=True,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
