# Generated by Django 5.0.14 on 2026-04-10 14:05

from django.db import migrations


def _drop_client_session_notes_foreign_keys(apps, schema_editor):
    connection = schema_editor.connection
    table_names = set(connection.introspection.table_names())
    if "client_session_notes" not in table_names:
        return

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                DO $$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT conname
                        FROM pg_constraint
                        WHERE conrelid = 'client_session_notes'::regclass
                          AND contype = 'f'
                    LOOP
                        EXECUTE format(
                            'ALTER TABLE client_session_notes DROP CONSTRAINT IF EXISTS %I',
                            r.conname
                        );
                    END LOOP;
                END
                $$;
                """
            )
            return

        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "client_session_notes")
        }
        if "legacy_client_ref_id" not in columns:
            return


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0016_clientsessionnote_bridge_refs"),
    ]

    operations = [
        migrations.RunPython(
            _drop_client_session_notes_foreign_keys,
            migrations.RunPython.noop,
        ),
    ]
