# Generated by Django 5.0.14 on 2026-03-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0003_partner_consultationrequest_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formerrecommendation",
            name="reasoning_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
