# Generated by Django 5.0.14 on 2026-03-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0004_formerrecommendation_reasoning_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturerecord",
            name="deidentified_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="landmark_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capturerecord",
            name="privacy_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faceanalysis",
            name="landmark_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
