# Generated by Django 5.0.14 on 2026-03-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0005_capturerecord_deidentified_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="consent_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="partner",
            name="consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
