# Generated by Django 5.0.14 on 2026-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0006_partner_consent_snapshot_partner_consented_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="formerrecommendation",
            name="regeneration_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
