# Generated by Django 5.0.14 on 2026-03-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0007_formerrecommendation_regeneration_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturerecord",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="capturerecord",
            name="original_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="capturerecord",
            name="processed_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
